from typing import Protocol, runtime_checkable, Any


@runtime_checkable
class IProcessService(Protocol):
    def toggle(self) -> None: ...
    def start(self) -> None: ...
    def stop(self) -> bool: ...
    def refresh_status(self) -> None: ...
    def monitor(self) -> None: ...


@runtime_checkable
class IVersionService(Protocol):
    def refresh(self, scope: str = "all") -> None: ...


@runtime_checkable
class IConfigService(Protocol):
    def load(self) -> dict: ...
    def save(self, data: dict | None = None) -> None: ...
    def get(self, key_path: str, default: Any = None) -> Any: ...
    def set(self, key_path: str, value: Any) -> None: ...


@runtime_checkable
class IPackageService(Protocol):
    def show_version(self, name: str) -> str | None: ...
    def install(self, name: str, index_url: str | None = None, upgrade: bool = True) -> dict: ...