COLORS = {
    "BG": "#FFFFFF",
    "SIDEBAR_BG": "#20252B",
    "SIDEBAR_ACTIVE": "#2D343C",
    "TEXT": "#1F2328",
    "TEXT_MUTED": "#5F6870",
    "ACCENT": "#2F6EF6",
    "ACCENT_HOVER": "#2760DB",
    "ACCENT_ACTIVE": "#1F52BE",
    "BORDER": "#D0D5DB",
}

LAUNCH_BUTTON_CENTER = False
CARD_BORDER_COLOR = "#E3E7EB"
CARD_BG = "#FFFFFF"
SEPARATOR_COLOR = "#E3E7EB"
LEFT_RIGHT_GAP = 56
MAX_CONTENT_WIDTH = 1320

SHOW_SIDEBAR_DIVIDER = True
SIDEBAR_DIVIDER_COLOR = "#E2E5E9"
SIDEBAR_DIVIDER_SHADOW = True
SHADOW_WIDTH = 6

SECTION_TITLE_FONT = ("Microsoft YaHei", 18, "bold")
INTERNAL_HEAD_LABEL_FONT = ("Microsoft YaHei", 14, "bold")
BODY_FONT = ("Microsoft YaHei", 10)